#!/bin/sh

tmux -S /tmp/pair has-session -t workenv
if [[ $? == 1 ]] ; then
  pushd /Volumes/Analog/super-banner
  tmux -S /tmp/pair new-session -d -s workenv -n Vim
  tmux -S /tmp/pair new-window -t workenv -n Super-Banner
  cd /Volumes/Analog/cookbooks
  tmux -S /tmp/pair new-window -t workenv -n Cookbooks
  tmux -S /tmp/pair select-window -t workenv:Vim
  popd
fi
tmux -S /tmp/pair -2 attach -t workenv
